### ISSUE TITLE
How do you work with JMS-serializer ?

### ISSUE THREAD

**Issue by laudeco** [matteosister/patch-manager#4]
Hello,
I try to work your lib together with JMS Serializer, but I have a conflict on PHPCollection (0.2 and you 0.4) how can I solve it ?

How do you work with JMS ?

Cheers
L.

**Comment by matteosister** [comment]
did you find a solution? As far as I know the jms serializer [requires ~0.1](https://github.com/schmittjoh/serializer/blob/master/composer.json#L18), so 0.4 is ok!

**Comment by laudeco** [comment]
Yes I found a solution.
Thanks
L.
